### ISSUE TITLE
Mobile User cannot joined to the Call

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#1]
## Steps to Reproduce

1. Join a call withx with Chrome browser(Version 107.0.5304.62 (Official Build) (x86_64)) in laptop
2. Join a call with Chrome in iOS 

## Expected Behaviour
mobile user and desktop user should talk and see each other

## Actual Behaviour
Desktop user cannot see the mobile user. 
<img width="400" alt="Screenshot 2022-10-28 at 08 36 24" src="https://user-images.githubusercontent.com/3456251/198511779-79c462f4-c4ab-43b8-beea-ccfb71391ace.png">

Mobile user sees the desktop user 

<img width="300" alt="Screenshot 2022-10-28 at 08 36 24" src="https://user-images.githubusercontent.com/3456251/198511888-905d8fe3-0027-40b4-8d49-e196beb802d8.PNG">

**Comment by burak-58** [comment]
Fixed by:
https://github.com/ant-media/conference-call-application/commit/dd392198df10df423d1353aebfd4653d1deafa67
