### ISSUE TITLE
How can we edit the code and deploy again from github

### ISSUE THREAD

**Issue by hkmsadek** [ant-media/conference-call-application#105]
I would like to modify the react code and then re upload. How can I do this?

**Comment by USAMAWIZARD** [comment]
for building from src and then deploying the application on server.

Clone and Make changes 
1. git clone https://github.com/ant-media/conference-call-application.git
2. cd conference-call-application/react
3. npm install
4. Make Your required changes
5. npm start (Verify if everything is working as expected)
6. cd ..

Deploy To A Server 
8. sudo ./create-war.sh
9. a war file will be created in ./webapp/target/
10. got to ant media dashbord 
11. Create new application by selecting the war file. 
![image](https://github.com/ant-media/conference-call-application/assets/47350008/75002a90-5477-4596-8ad6-e5493574cf15)

**Comment by burak-58** [comment]
Thank you @USAMAWIZARD ,
I think create-war.sh script works on Ubuntu and requires maven and Java.

**Comment by USAMAWIZARD** [comment]
your welcome @burak-58  abi Thanks for confirming it

**Comment by USAMAWIZARD** [comment]
@hkmsadek were you able to check the solution
