### ISSUE TITLE
New Drawer Content Keeps Refreshing

### ISSUE THREAD

**Issue by ScottStick** [ant-media/conference-call-application#121]
I've created a new button to open a new drawer and tab, using the participant list JS as a guide. I've been successful in getting that far, but the drawer content keeps refreshing and the settings I make in this drawer keep getting reset. I'm guessing that it's probably due to the participant list drawer periodically updating its list of participants who are still in the meeting room, but I cannot find the script responsible for it.

Does anyone know where I can locate this timed refresh/reset function? I suppose it's somewhere in ParticipantListDrawer.js or ParticipantTab.js in react/src/Components, or maybe MeetingRoom.js in react/src/Pages, but I could be completely wrong!

**Comment by mekya** [comment]
Thank you @ScottStick 

I've put this to the Sprint plan to let one of my colleague help you.

**Comment by ScottStick** [comment]
Hi @mekya

Thank you for passing on my issue.

I've narrowed it down to the TabPanel component, which wraps my new TabGrid content, though I can't say _why_ the TabPanel keeps re-rendering. I've noticed that the re-render interval coincides precisely with the poor network warning interval, which is driving me crazy, but one issue at a time!

**Comment by mekya** [comment]
Hi @ScottStick,

Thank you very much.  My colleague has also improved the "poor network warning" and I'm not sure if it's merged. 

@burak-58, may i ask you just give some idea for @ScottStick because he's trying to understand and fixing the problem. 

Cheers

**Comment by burak-58** [comment]
Hi @ScottStick ,
Thanks for your interest. I have checked the ParticipantListDrawer. It uses Context provided by Antmedia.js I think there are lots of variable provided by Antmedia.js there and they may cause unnecessary rendering on the components. We can check possible optimisations there. 
Do you have an idea or suggestion @ScottStick? Also if you have a solution we are open to PRs.

**Comment by ScottStick** [comment]
Hi Burak,

I’m sorry it has taken so long to respond.

I gave up on adding a new Drawer and instead, created a new Dialog component that contains the Select components. I did notice that if I pushed objects to arrays that map each Select component’s MenuItems within the export function, the arrays keep growing because the same objects keep getting pushed every few seconds:

let array1 = [];
let array2 = [];

…

export newDialog(props) {
      const objs1 = Objects.objects1;
      const objs2 = Objects.objects2;
      objects1.forEach(function (param1) {
            var name = param1.name;
            array1.push({prop1: name.prop1, prop2: name.prop2});
});
objects2.forEach(function (param2) {
      var name = param2.name;
      array2.push({prop1: name.prop1, prop2: name.prop2});
});

…

return (
      <Dialog>

            …

            <Select>
                  {array1.map(item1 => (
                        <MenuItem key={item1.key} value={item1.value}>{item1.label}</MenuItem>
                  ))}
            </Select>
            <Select>
                  {array2.map(item2 => (
                        <MenuItem key={item2.key} value={item2.value}>{item2.label}</MenuItem>
                  ))}
            </Select>

            …

      </Dialog>
);
}

But if I move the highlighted block of code before/outside the export declaration, the arrays, and therefore, the MenuItems are only rendered once, the way they are supposed to.

I still don’t know what is responsible for the continual re-rendering, but I agree, it must be something in the AntMedia.js file. I’ve noticed that the timing of the re-render aligns with the roomInfoHandleJob interval of 5000 msec, but I haven’t traced it any further yet.

I hope that all makes sense!

Kind regards,

Scott

[Logo  Description automatically generated with medium confidence]<https://www.montysp.com.au/>

[A blue and white logo  Description automatically generated with low confidence]<https://www.dciatechnologies.com.au/>

***@***.***
Scott Stickland
PhD Music (Newcastle); MMusTech (Newcastle); BEd(Sec) – Music (Melbourne)

Phone: 613 9461-1518
Mobile: 61478 221-209
Email: ***@***.******@***.***>

www.montysp.com.au<http://www.montysp.com.au/>

[A blue circle with white letters on it  Description automatically generated with medium confidence]<https://www.linkedin.com/in/scott-stickland-phduon/>  [THE NEW LATEST FACEBOOK LOGO PNG TRANSPARENT 2022] <https://www.facebook.com/sstickland70/>    [1 - Researchgate Logo Circle, HD Png Download , Transparent ...] <https://www.researchgate.net/profile/Scott-Stickland>   [Google Scholar Academic journal Google logo Education, google, text,  trademark png | PNGEgg] <https://scholar.google.com.au/citations?user=q-eB4_8AAAAJ&hl=en>


Une chose qui m’humilie profondément est de voir que le génie humain a des limites, quand la bêtise humaine n’en a pas. Alexandre Dumas

**Comment by mekya** [comment]
Hi @ScottStick,

Thank you for explanation. Even if this issue is on our radar, I'm not sure if @burak-58 can give a response soon because there is a good demand to the Ant Media Server from enterprise and almost all team is loaded.

Anyway, I'll notify the @burak-58 for that

Cheers
