### ISSUE TITLE
Issue with /webapp/pom.xml

### ISSUE THREAD

**Issue by ScottStick** [ant-media/conference-call-application#126]
Just tried creating a new WAR file to implement some of the latest changes in my AWS conference app, but I keep getting a fatal error when running the Maven clean install line:
`Non-resolvable parent POM for io.antmedia.webrtc:ConferenceCall:2.6.3-SNAPSHOT: Could not find artifact io.antmedia:parent:pom:2.6.3-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 10`

I tried inserting
`<plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>
        </configuration>
      </plugin>`
at the top of the plugins list, but that made no difference.

Has anyone come across this problem and does anyone know how to resolve it?

**Comment by Mohit-3196** [comment]
Hi @ScottStick ,
Hope you are doing well.

Let me try to make these tests on my end and update you on the error.
Meanwhile, is it possible for you to provide some details about how you are creating the war file, etc?

Thank you

**Comment by ScottStick** [comment]
Hi Mohit,

Thanks for looking into this for me.

I create the war file using the same procedure as the createwar shell file by manually executing the React build command first:

projectfolder>react>npm run build

Then just copy/paste and execute the rest to get the war file once I know the build completed successfully:

cd ..
rm webapp/src/main/webapp/static/css/*
rm webapp/src/main/webapp/static/js/*
cp -a react/build/. webapp/src/main/webapp
cd webapp
mvn clean install -DskipTests -Dgpg.skip=true --quiet

While running the clean install, I always get an error message that maven ignores and continues with the install process:

[ERROR] Error fetching link: /mnt/c/DCIA Dev/webapp/target/javadoc-bundle-options. Ignored it.

It doesn’t seem to affect the conference app, but it’s curious that it appears every time. Is there a fix for this error? In the meantime, I changed the parent project version back to 2.6.0-SNAPSHOT in the pom.xml file so I can keep working on the conference call app.

While I’ve got you, can you please recommend what I should do regarding the initial react>npm install command? During the install process, I get the following warnings:


  *   ***@***.***: Library is deprecated.
  *   ***@***.***: Library is deprecated, use @rollup/plugin-terser.
  *   ***@***.***: Use your platform’s native performance.now() and performance.timeOrigin.
  *   ***@***.***: Use @jridgewell/sourcemap-codec.
  *   ***@***.***: Legacy, new code should use the URLSearchParams API instead.
  *   ***@***.***: Use ***@***.***
  *   ***@***.***: Upgrade to v2.x.x.

Once the install has completed, npm identifies 9 vulnerabilities (3 Moderate, 6 High). Should I resolve the vulnerabilities and/or the warnings, particularly those related to ***@***.***, ***@***.***, ***@***.*** and ***@***.***, then try the install process again? Your assistance with this would be hugely appreciated.

I hope this all makes sense!

Kind regards,

Scott

[Logo  Description automatically generated with medium confidence]<https://www.montysp.com.au/>

[A blue and white logo  Description automatically generated with low confidence]<https://www.dciatechnologies.com.au/>

***@***.***
Scott Stickland
PhD Music (Newcastle); MMusTech (Newcastle); BEd(Sec) – Music (Melbourne)

Phone: 613 9461-1518
Mobile: 61478 221-209
Email: ***@***.******@***.***>

www.montysp.com.au<http://www.montysp.com.au/>

[A blue circle with white letters on it  Description automatically generated with medium confidence]<https://www.linkedin.com/in/scott-stickland-phduon/>  [THE NEW LATEST FACEBOOK LOGO PNG TRANSPARENT 2022] <https://www.facebook.com/sstickland70/>    [1 - Researchgate Logo Circle, HD Png Download , Transparent ...] <https://www.researchgate.net/profile/Scott-Stickland>   [Google Scholar Academic journal Google logo Education, google, text,  trademark png | PNGEgg] <https://scholar.google.com.au/citations?user=q-eB4_8AAAAJ&hl=en>


Une chose qui m’humilie profondément est de voir que le génie humain a des limites, quand la bêtise humaine n’en a pas. Alexandre Dumas

**Comment by Mohit-3196** [comment]
Hi @ScottStick ,
Thank you for the details.

I tried these on my end as well and the below error
`Non-resolvable parent POM for io.antmedia.webrtc:ConferenceCall:2.6.3-SNAPSHOT: Could not find artifact io.antmedia:parent:pom:2.6.3-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 10`

comes if the ant-media-server-parent is not built.

So, you need to build it first.
Just run,
```
$ git clone https://github.com/ant-media/ant-media-server-parent.git
$ cd ant-media-server-parent/
$ mvn clean install -Dgpg.skip=true
$ cd ..
```
https://antmedia.io/docs/guides/advanced-usage/Building-AMS-from-source/#linux-ubuntu
And then try building the conference application war file with `createwar.sh` or manually.
It worked for me.

Let me know if you face any issues with these.

And I will check your other queries to answer those as well.

Thank you

**Comment by ScottStick** [comment]
Hi Mohit,

Thank you for replying so quickly. Building the ant-media-server-parent resolved the issue beautifully! I still get the following error when executing the final line of the createwar.sh file:

webapp$ mvn clean install -DskipTests -Dgpg.skip=true --quiet
[ERROR] Error fetching link: /project_folder/webapp/target/javadoc-bundle-options. Ignored it.

Despite the error, the clean install still creates the war file, which appears to work as expected.

Thanks for your help – it’s greatly appreciated.

Kind regards,

Scott

[Logo  Description automatically generated with medium confidence]<https://www.montysp.com.au/>

[A blue and white logo  Description automatically generated with low confidence]<https://www.dciatechnologies.com.au/>

***@***.***
Scott Stickland
PhD Music (Newcastle); MMusTech (Newcastle); BEd(Sec) – Music (Melbourne)

Phone: 03 9461-1518
Mobile: 0478 221-209
Email: ***@***.******@***.***>

www.montysp.com.au<http://www.montysp.com.au/>

[A blue circle with white letters on it  Description automatically generated with medium confidence]<https://www.linkedin.com/in/scott-stickland-phduon/>  [THE NEW LATEST FACEBOOK LOGO PNG TRANSPARENT 2022] <https://www.facebook.com/sstickland70/>    [1 - Researchgate Logo Circle, HD Png Download , Transparent ...] <https://www.researchgate.net/profile/Scott-Stickland>   [Google Scholar Academic journal Google logo Education, google, text,  trademark png | PNGEgg] <https://scholar.google.com.au/citations?user=q-eB4_8AAAAJ&hl=en>


Une chose qui m’humilie profondément est de voir que le génie humain a des limites, quand la bêtise humaine n’en a pas. Alexandre Dumas

**Comment by mekya** [comment]
Just an update @ScottStick 

I've added the repositories to the pom.xml to not force any users to clone and build the parent project again. In this way, we can save time. 
https://github.com/ant-media/conference-call-application/pull/127

@Mohit-3196 you can merge it if it works for you and You can proceed the issue with @ScottStick

**Comment by Mohit-3196** [comment]
Hi @ScottStick ,
Thank you to you as well :)

`webapp$ mvn clean install -DskipTests -Dgpg.skip=true --quiet
[ERROR] Error fetching link: /project_folder/webapp/target/javadoc-bundle-options. Ignored it.`
It is not directly related to the AMS because here it tries to get javadoc bundle and the ignores it. You can ignore the message as it will not affect the application.

Also, if you run
`mvn clean install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -Dgpg.skip=true`
then the error will not come.

Thank you

**Comment by Mohit-3196** [comment]
Also, Thank you @mekya abi for the PR #127 
It was failing on the CI so therefore I couldn't merge it yet.

Me and @burak-58 abi had a discussion about it and we are trying to resolve the build failing issue.
FYI, please.

Thank you.

**Comment by ScottStick** [comment]
Hi @Mohit-3196,

Thanks for confirming that the fetching link error is nothing to worry about and the alternative mvn clean install snippet. Your help is always greatly appreciated.
![bitmoji](https://sdk.bitmoji.com/render/panel/8b204e29-0864-4a9b-b74f-2c4a8be16f8e-623252b0-9f79-4c35-8a68-a9acd7be58db-v1.png?transparent=1&palette=1&width=246)

**Comment by Mohit-3196** [comment]
Thank you @ScottStick 
You are the best :)

**Comment by Mohit-3196** [comment]
Hi @ScottStick ,
I think all's good here so I will be closing this issue now.
Let me know if there's anything left for you by reopening it.

Thank you.
