### ISSUE TITLE
Record a video/write documentation about component usage of circle app

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/conference-call-application#137]

**Comment by timantmedia** [comment]
@mustafaboleken should we create a new directory for plugins and applications in docs for your documentation here https://github.com/ant-media/ant-media-documentation/pull/116

**Comment by mustafaboleken** [comment]
@timantmedia In my opinion, we don't need such separation. In the future, if there are 4-5 pages about different plugins/applications we can move such an approach.
