### ISSUE TITLE
Sometimes users videos are not visible 

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#139]
We can see the users sometimes in the call

**Comment by ScottStick** [comment]
I can confirm this happens, too. 

I've at least been able to work out that if a user (User A) mutes his/her webcam, and User A's VideoCard displays an Avatar, if another user (User B) joins the conference, User B's MeetingRoom layout does not include User A's VideoCard, but User A's MeetingRoom layout includes both User A and User B VideoCards. 

Then, if User A unmutes his/her webcam, User B's MeetingRoom layout will update to include User A's VideoCard.

I hope this will help point to the issue!
