### ISSUE TITLE
Black Screen tile stays when user left the room

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#140]
1. Join room  as user1
2. Join the same room as user2
3. Leave the room as user1 

Expected
user2 can only see his self in the screen

Actual
user2 also see a black screen as in the image below
<img width="1667" alt="Screenshot 2023-08-13 at 19 02 19" src="https://github.com/ant-media/conference-call-application/assets/3456251/250bec76-25ad-4e09-a92b-44093c0f7929">

Possible solution place is here 
https://github.com/ant-media/conference-call-application/blob/main/react/src/Components/Cards/VideoCard.js#L49C1-L50C1

**Comment by mustafaboleken** [comment]
I tested with the possible solution you mentioned and it works.
