### ISSUE TITLE
It takes about 5 seconds to see participants

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#141]
1. Let user1 join the room
2. Let user2 join the room

Expected
user2 start to see user1 in a couple of seconds

Actual
It takes about 5 seconds to see the user1

**Comment by mustafaboleken** [comment]
I found a way to improve it but for a permanent solution, we will discuss in an internal meeting at Wednesday.

**Comment by mustafaboleken** [comment]
I checked the flow but couldn't find any way so far.
