### ISSUE TITLE
Reconnect scenario frequently fails to play remote streams 

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#142]
Try the following scenario in a couple of times if you don't reproduce it in the first attempt

1. Let user1 join the call in chrome
2. Let user2 join the call in mobile(safari)
3. Disconnect network for user1
4. Wait about 15 seconds
5. Connect network for user1

Actual:
User1 cannot see the user2 which is not expected
User2 can see the user1 which is expected

Expected:
User1 start to see the user2 again

**Comment by mustafaboleken** [comment]
I found the problem but for a permanent solution, we will discuss in an internal meeting at Wednesday.
