### ISSUE TITLE
Reconnect scenario cannot be successfull in safari

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#143]
1. Let user1 join the room in mobile safari or desktop safari
2. Let user2 join the room in another desktop
3. Disconnect user1 from the network
4. Wait 15 seconds
5. Reconnect user1 network again

Expected:
User2 starts to see the user1

Actual
User1 cannot join the room again and it throws following error all the time
<img width="1507" alt="Screenshot 2023-08-13 at 19 26 47" src="https://github.com/ant-media/conference-call-application/assets/3456251/4c330cee-6bc9-4d3f-a7db-aab011b274fb">

 
<img width="1507" alt="Screenshot 2023-08-13 at 19 27 13" src="https://github.com/ant-media/conference-call-application/assets/3456251/01737fa4-28bc-4f32-81c2-77dd2e2409c2">

**Comment by mustafaboleken** [comment]
I found the problem but for a permanent solution, we will discuss in an internal meeting at Wednesday.
