### ISSUE TITLE
Can We Create Multiple Data Channels?

### ISSUE THREAD

**Issue by ScottStick** [ant-media/conference-call-application#149]
Is it possible to create a separate data channel to the default channel used for chat messages? 

I know WebRTC allows multiple data channels in a single Peer Connection, all using the same stream, without having to negotiate multiple offer/answer exchanges beyond the initial SDP exchange that establishes the default data channel. I want to create a semi-reliable data channel, implementing maxRetransmits, that will send/receive arrayBuffer (32) messaging during the conference meeting. 

At the moment, I'm using the default data channel for chat _and_ arrayBuffer messaging, but I need to keep these data streams separate. I'm having to stringify the arrayBuffer messages before sending and parse them upon receiving, which increases the latency that is already a bit too high given that the data channel appears to be configured as reliable. I've also discovered that using the existing webRTCAdaptor.sendData() method sends multiple copies of the stringified arrayBuffer messages for some reason.

In AntMedia.js, I've included additional lines of code:

```
const sqrBrkts = /[[\]]/; 
let [aDataMessage, setADataMessage] = useState("");
let [bDataMessage, setBDataMessage] = useState("");

function handleNotificationEvent(obj) {
  var notificationEvent = JSON.parse(obj.data);
  if (notificationEvent != null && typeof notificationEvent == "object") {
    ...

    else if (eventType === "MESSAGE_RECEIVED") {
      if (new RegExp(sqrBrkts).test(notificationEvent.message)) {
        handleIncomingArray(notificationEvent.message);
      } else {
        calculate_scroll_height();
        ...
      }
    }
  }
}

function handleIncomingArray(msg) {
  msg = JSON.parse(msg);
  var aData = msg[1];
  var status = aData[0];
  if (status < 240) {
    setADataMessage(msg);
  }
  if (status >= 240) {
    setBDataMessage(msg);
  }
}

function handleSendADataMessage(message) {
  if (publishStreamId) {
    let iceState = webRTCAdaptor.iceConnectionState(publishStreamId);
    if (
      ...
    ) {
      if (message === "debugme") {
        ...
      }
      webRTCAdaptor.sendData(
        publishStreamId,
        JSON.stringify({
          eventType: "MESSAGE_RECEIVED",
          message: message,
          userId: streamName
          })
        );
      }
    }
  }

function handleSendBDataMessage(message) {
  if (publishStreamId) {
    let iceState = webRTCAdaptor.iceConnectionState(publishStreamId);
    if (
     ...
    ) {
      if (message === "debugme") {
        ...
      }
      webRTCAdaptor.sendData(
        publishStreamId,
        JSON.stringify({
          eventType: "MESSAGE_RECEIVED",
          message: message,
          userId: streamName
          })
        );
      }
    }
  }
...
return (!initialized ? <></> :
  <Grid container className="App">
    <Grid
      container
      ...
    >
      <ConferenceContext.Provider
        value={{
          isScreenShared,
          ...
          aDataMessage,
          bDataMessage,
          handleSendADataMessage,
          handleSendBDataMessage,
          ...
      </ConferenceContext.Provider>
    </Grid>
  </Grid>
);
```
I'd much prefer to edit AntMedia.js as little as possible, if at all.

Any and all feedback, suggestions, comments, etc. are most welcome and greatly appreciated!

**Comment by ScottStick** [comment]
I guess this one is in the "too hard" basket? Please add this information in with my issue about the data channel behaviour that keeps sending the last message over and over.

**Comment by mekya** [comment]
Hi @ScottStick,
Thank you for creating the issue. I've just put this to the backlog. We just plan things according to the priority. We'll put this to this week's plan according to the availability of the team.  
 
If you want us to increase the priority of the issues you create, let's discuss what we can have win-win relation together via contact@antmedia.io

Have a great day. 

Regards
Oz
