### ISSUE TITLE
When reconnect due to network fluctuations, it causes multiple tiles

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#161]
Steps
1. Connect the room from a fluctuating network
2. Observe that it reconnects due to network conditions
3. Check the tile count as in the image

Expected:
There should be one tile with label "You"

Actual:
There are 4 tiles with label "You". Check the image 

<img width="1711" alt="Screenshot 2023-11-30 at 09 58 15" src="https://github.com/ant-media/conference-call-application/assets/3456251/ceff7e30-be0e-4f18-bf9c-c6ac722e0439">

**Comment by USAMAWIZARD** [comment]
Here is the recorded video of me testing with the Old Commit and then master branch
Commit id   737da1ccdb5795cf8e53a2b89b1be0f8a0e11c08

( Fist part in the video is using the old commit )
I joined the meeting with my pc and mobile device 5 guys from the pc and 1 from mobile 
disable the network on my mobile
enable the network on my mobile

Second Test in the video is using the master branch.


https://github.com/ant-media/conference-call-application/assets/47350008/81784a62-24f6-49c3-9fdb-4d3091a32f52
