### ISSUE TITLE
Emojis are not clickable if one shares screen 

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#163]
Just check the image. Emojis are not clickable

<img width="1652" alt="Screenshot 2023-12-01 at 14 10 25" src="https://github.com/ant-media/conference-call-application/assets/3456251/591463b1-e5a9-4c7c-966d-f01fc1d3a3fe">

**Comment by mustafaboleken** [comment]
![Screenshot 2023-12-03 at 15 12 29](https://github.com/ant-media/conference-call-application/assets/23143596/80f6ff0a-248a-40e5-ad85-41c7dacd5a4e)
