### ISSUE TITLE
Add label background to make it readable in all cases for emojis 

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#164]
Just check the image. The one who sends emoji is not readable. 
<img width="1652" alt="Screenshot 2023-12-01 at 14 19 16" src="https://github.com/ant-media/conference-call-application/assets/3456251/dc8ff656-ea40-4eb0-a7cb-c89f0166b499">

**Comment by mustafaboleken** [comment]
It's fixed inside: https://github.com/ant-media/conference-call-application/pull/157
