### ISSUE TITLE
Tile count is not correct 

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#165]
1. Start the meeting with 6 people. 
2. Some of them left the room and 2 are left as in the image
3. There are 3 tiles. It should be 2

<img width="1748" alt="Screenshot 2023-11-27 at 16 14 35" src="https://github.com/ant-media/conference-call-application/assets/3456251/3235816b-25d0-43c4-8dbc-b22b2e7305c4">

**Comment by mustafaboleken** [comment]
Gitlab: https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/647
