### ISSUE TITLE
Make it mobile friendly 

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#166]
![IMG_9465](https://github.com/ant-media/conference-call-application/assets/3456251/4217bbe1-1ed6-484b-b407-55d91ae220f9)
- [ ] Icons are not clickable and visible

![IMG_9464](https://github.com/ant-media/conference-call-application/assets/3456251/ec451313-13f6-470a-a4e7-223cbbcde1b5)
-[ ] Single view does not fill the screen. I think views can fill the screen in all environments

![IMG_9463](https://github.com/ant-media/conference-call-application/assets/3456251/5557d384-0ade-4eb6-a831-4208228910ac)
- [x] Icons are not clickable 
- [ ] Column count, number of tiles should be arranged
- [ ] Mobile user should be visible in portrait mode if device is in portrait mode. In the screenshot above, User with label "You" should be visible in portrait mode

**Comment by USAMAWIZARD** [comment]
**1. Icon is not clickable** 
![image](https://github.com/ant-media/conference-call-application/assets/47350008/b77e1268-5295-4b2f-8d29-b2bb53eee5ac)

3. "You" should be visible in portrait mode
are we expecting something like this 
![image](https://github.com/ant-media/conference-call-application/assets/47350008/6cc58dee-59e9-47db-ab5d-d1005ad36169)

**Comment by mustafaboleken** [comment]
![WhatsApp Image 2024-01-30 at 13 24 17](https://github.com/ant-media/conference-call-application/assets/23143596/5182f8f9-c5cd-48c7-a158-17bc5cb4dc45)
