### ISSUE TITLE
User's view is stuck in the screen when it leaves directly closing the tab

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#171]
Steps
1. User1, User2 and User3 join the call
2. User2 leaves the call by just closing the tab/browser directly 

Expected behavior:
User2's view should be removed from User1 screen in a short time(1-2seconds)

Actual behaviour: 
User2's view freezes and it's removed after 5-10 seconds 

"Nur" has left the room below but it was visible for about 5-10 seconds
<img width="1726" alt="Screenshot 2023-12-06 at 12 10 20" src="https://github.com/ant-media/conference-call-application/assets/3456251/0c8a53f5-a175-497e-b509-13df6fc75c36">

"Burak" has lef the room below but it was visible for about 5-10 seconds
<img width="1726" alt="Screenshot 2023-12-08 at 14 49 06" src="https://github.com/ant-media/conference-call-application/assets/3456251/f166fc12-1627-4b02-b6c8-2747b094b43e">

**Comment by USAMAWIZARD** [comment]
Not reproducible
