### ISSUE TITLE
One user cannot see the other user

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#197]
Environment:
Circle is deployed to the Ant Media Server which is the latest master branch(2.8.0-SNAPSHOT) build. 
 

Steps
1. Start a call from one user from Chrome browser - first user
2. Let the another user join the call - second user. (We don't know the browser of the second user. There is a similar problem in one firefox version) 

Expectation:
Both users should see each other

Actual:
Users cannot see or hear each other. First user see the second user in the participant list

![WhatsApp Image 2024-01-15 at 14 14 53](https://github.com/ant-media/conference-call-application/assets/3456251/ef4ef046-a8ac-4fe4-ada5-d295d1024796)

**Comment by mustafaboleken** [comment]
It looks like they faced this issue https://github.com/ant-media/Ant-Media-Server/issues/6012 @mekya

**Comment by mustafaboleken** [comment]
Can you ask if the 3rd person enters the room, is it solved? If yes, we already working on this issue.
