### ISSUE TITLE
Camera stays open when someone lefts the room

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#2]
Steps to reproduce
1. Join to the room 
2. Just close the mic and camera in the call 
3. Left the room 

Expected Behavior
Camera and Microphone has closed

Actual Behavior
Camera or mic is still open in step 2 and step 3. Check the camera sign on the browser tab   
<img width="1516" alt="Screenshot 2022-10-31 at 09 40 31" src="https://user-images.githubusercontent.com/3456251/199012131-ddb08d09-b77e-4375-b12a-6881f98ca987.png">

<img width="1516" alt="Screenshot 2022-11-02 at 15 44 48" src="https://user-images.githubusercontent.com/3456251/199493276-683caf42-44bf-42ca-b7c2-a1ff03a023f6.png">

**Comment by burak-58** [comment]
Fixed by:
https://github.com/ant-media/conference-call-application/commit/410e97681e62cb7e8f1af5f6e3835d1ab60cb415
