### ISSUE TITLE
Speed test before login

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#23]
Provide an option to let the user make a speed test before joining the call 

- This option(enableSpeedTest) can be enabled/disabled.
- If the `enableSpeedTest`  is `true`, make a speed test before login
  - Show the test result in a basic window in the same page and let the user Proceed or Cancel
- If the `enableSpeedTest` is `true`, let the user login directly without any speed test before login

In Speed Test
- Bitrate value should be configurable. Default value can be 1.5Mbps
- Packet Lost should be less than %1
- RTT should be less than 50ms
- Jitter should be less than 30ms

Result
- If all conditions met, say the connection Good
- If RTT is 50-150ms or packet lost %1-2.5 or jitter 30ms - 80ms or bandwidth is %80-100 of the bitrate, say the connection Fair
- If RTT is 150ms or packet lost is >%2.5 or jitter >80ms or bandwidth is <%80 of the bitrate , say the connection Bad

**Comment by mustafaboleken** [comment]
This feature is merged. So, I'm closing this issue.
