### ISSUE TITLE
Circle: After reconnection getting own audio which causes echo

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/conference-call-application#253]
This is the scenario I encounter this problem

1. I connect my laptop to internet through iphone USB tethering.(There is no other Wi-Fi connection to internet)
2. I join the video call
3. During the call, USB cable is disconnected so that internet connection is dropped
4. I connect USB cable again and Circle is connected to the room again

Expected:
I expect to proceed without any audio/video issue

Actual:
When I re-join the call and start speaking, I also start to hear my voice at the same time. There is an echo.

**Comment by mustafaboleken** [comment]
@burak-58 finds the reason and solved it in the server side codes.

**Comment by burak-58** [comment]
https://github.com/ant-media/Ant-Media-Server/issues/6094

**Comment by mekya** [comment]
It's fixed in enterprise side and merged
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/702
