### ISSUE TITLE
work from phone

### ISSUE THREAD

**Issue by studentAlanMorgan** [ant-media/conference-call-application#258]
No screen sharing when using from a phone

**Comment by mustafaboleken** [comment]
Hi @studentAlanMorgan 

getDisplayMedia() is not supported on Android and iOS environments. You can check the compatibility table below. If you need screen sharing feature in mobile devices, you need to have mobile application.

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility
