### ISSUE TITLE
Missing tile in case of second screen share

### ISSUE THREAD

**Issue by burak-58** [ant-media/conference-call-application#262]
Scenario:
1. Join a room with 2 participant
2. Share screen by participant1, see it is pinned for both participant
3. Share screen by participant2,  see it is pinned for both participant
4. problem: participant1's screen is not have any tile even if there is free video track

Cause:
1. screen share doesn't have audio so video track assignment is not triggered
2. VTA algorithm shoud make available current assigned video track for a stream if user force to assign another video track for that stream

**Comment by mustafaboleken** [comment]
Enterprise code: https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/713

**Comment by mekya** [comment]
Hi @mustafaboleken ,
The enterprise side is merged into the master. Thank you for the fix.

**Comment by mustafaboleken** [comment]
> Hi @mustafaboleken , The enterprise side is merged into the master. Thank you for the fix.

I'm letting @burak-58 abi to review conference side.
