### ISSUE TITLE
Cant Create room ,  WebSocket Error

### ISSUE THREAD

**Issue by brixxnatt** [ant-media/conference-call-application#269]
Cant Create room ,  WebSocket Error
Just installed on a fresh Enterprize edition , installed the war file
when i want to creat a room i cant create

**Comment by mustafaboleken** [comment]
Hi @brixxnatt 

Can you send me your browser console log?

**Comment by brixxnatt** [comment]
it was my error , i was on  a wrong port , how to prevent public from creating a room plz

**Comment by mustafaboleken** [comment]
You can follow the steps below:
- Open the management console
- Go to the conference application
- Open advance settings.
- Add/update the following fields 

settings.roomCreationPasswordEnabled = false
settings.roomCreationPassword = 123123

**Comment by mekya** [comment]
Hi Guys,
Then I'm closing this issue for the inactivity or it's already resolved. 

Please feel free to re-open if you think differently.

Cheers
Oz
