### ISSUE TITLE
how to remove a language

### ISSUE THREAD

**Issue by brixxnatt** [ant-media/conference-call-application#270]
please how to remove a language

thanks

**Comment by mustafaboleken** [comment]
Hi @brixxnatt 

You can remove any language from the list inside AvailableLanguages.js

**Comment by brixxnatt** [comment]
thanks for your answer , but i cant find the AvailableLanguages.js inside the war file

**Comment by mustafaboleken** [comment]
You cannot change it inside the war file. Instead of that, you need to clone the project, make the changes you need, and run the createwar.sh script on a Linux machine. It will produce a new war file for you.

https://github.com/ant-media/conference-call-application/tree/main/react/src/i18n

**Comment by mekya** [comment]
Hi Guys,
Then I'm closing this issue for the inactivity or it's already resolved.

Please feel free to re-open if you think differently.

Cheers
Oz
