### ISSUE TITLE
Selective track enablement according to participant role

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/conference-call-application#272]

**Comment by mustafaboleken** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/696

**Comment by mustafaboleken** [comment]
Enterprise: https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/698

**Comment by mekya** [comment]
It's not merged so I'm moving it 'in progress'
