### ISSUE TITLE
Inconsistent behavior when participants connect without a camera or deny microphone/video permissions, the server does not send video track assignments to current connected participants

### ISSUE THREAD

**Issue by DexterChanga** [ant-media/conference-call-application#292]
v2.8.2 (https://github.com/ant-media/conference-call-application/tree/v2.8.2)

**Reproduce scenario:**

 - Connect participant 1
 - Connect participant 2 with no camera or (easier way) deny camera/microphone permissions. 
 **Note:** I encounter the same behavior in both cases.

**Actual:**
 
Participant 1 does not receive a Video Track Assignment for participant 2. However, if participant 1 joins after participant 2 joins, they receive a Video Track Assignment.

**Expected:**

I should receive Video Tracks Assignments for all participants, regardless of when they enter the conference and if they have no camera or have been denied microphone/video permissions.

**Notes:**
- I encounter the same behavior on v2.9.0

**Comment by burak-58** [comment]
Hi @lastpeony,
Can you try the same scenario with 2.10.0 version?

**Comment by DexterChanga** [comment]
This seems to be fixed in 2.10. Thank you @burak-58
