### ISSUE TITLE
Users connect but can’t see or hear each other

### ISSUE THREAD

**Issue by Paulnk777** [ant-media/conference-call-application#3]
So far we have only had success with a meeting using MacBook and Chrome together. Safari doesn’t seem to work. But iPhones haven’t been consistent with us. Only got one iPhone to work and was using Chrome, but no one on the MacBooks could see or hear the person on the iPhone in the meeting. But the iPhone user could see them.

**Comment by mekya** [comment]
I've experienced the same behaviour as well in today's meeting. While I'm having this meeting, I also encounter that there are guys in the meeting but their tiles are not visible. Check the image below. There are 4 tiles in the panel but actually there are 9 people in the call. Maybe these two things are related to each other. 

@berk9595 @denizerisen do you have any idea about this problem? 

<img width="1516" alt="Screenshot 2022-11-08 at 09 03 12" src="https://user-images.githubusercontent.com/3456251/200500231-4cbe0547-6694-43c8-976c-bfda61d3e7a0.png">

**Comment by burak-58** [comment]
Fixed by:
https://github.com/ant-media/conference-call-application/commit/dd392198df10df423d1353aebfd4653d1deafa67
