### ISSUE TITLE
Entire screen cannot be shared in Safari browser on Mac for Circle

### ISSUE THREAD

**Issue by burak-58** [ant-media/conference-call-application#351]
**Reproduce scenario:**
1. Enter a Circle room by Safari browser in Mac
2. Start screen share for entire screen

**Expected:** It should share the screen
**Actual:** Screen sharing doesn't start

**Note:** You can share window or tab without issue. Problem is for entire screen.

**Comment by mekya** [comment]
I've checked these items and it seems that there is no problem. It's an ambiguous UI issue in MacOS and Apple has improved the screen sharing in MacOS 15.
