### ISSUE TITLE
Audio Distorsion when sharing tab

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/conference-call-application#53]
Reproduce scenario:

- Join conference call as publisher
- Open HTML page below in the second tab
- Share the conference call tab
- Sound of recording is distorted

[stream_screen_capture_video_audio.txt](https://github.com/ant-media/conference-call-application/files/10803559/stream_screen_capture_video_audio.txt)

**Comment by mekya** [comment]
In 2.7.0, we get the audio level from RTP headers and we don't use VolumeMeter so we don't encounter any kind of audio distortion issue anymore then I'm closing this issue and feel free to re-open if you encounter any audio distortion issue.
