### ISSUE TITLE
Even after all participants are left conference room is not removed

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/conference-call-application#61]
![Screenshot 2023-03-16 at 11 28 21](https://user-images.githubusercontent.com/23143596/225558936-526bd30d-2bce-42ad-8934-c1d1112f3644.jpg)

**Comment by mekya** [comment]
Hi @mustafaboleken ,

Do you have a reproduce scenario or it's happening all times?

**Comment by mustafaboleken** [comment]
After "Remove room info polling from server" commit, it looks fixed.

**Comment by mekya** [comment]
Hi @mustafaboleken ,

I don't understand which commit you mean. Could you give a link to the commit?

**Comment by mustafaboleken** [comment]
> 

https://github.com/ant-media/StreamApp/pull/350

**Comment by mekya** [comment]
Thank you
