### ISSUE TITLE
Messages always scroll up and it's an annoying experience  

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#66]
- I try to scroll down the message to see the new messages
- It scrolls up automatically and I cannot see the latest messages
- Check the screenshot 

<img width="1525" alt="Screenshot 2023-03-30 at 15 49 12" src="https://user-images.githubusercontent.com/3456251/228841247-71a6b4e1-8835-4bba-8bf5-4a9133af7789.png">

**Comment by mekya** [comment]
Please revew and merge @mustafaboleken

**Comment by mustafaboleken** [comment]
I review and merge it to main
