### ISSUE TITLE
After screen share is stopped, publishing video can't be started

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/conference-call-application#87]
1-Join conference call room
2- Share your screen
3- Stop sharing screen
4- No video (own) published 
5- It never comes up

**Comment by Jhoubert** [comment]
Hey @akiziltoprak, just a note only happens when you're presenting and you stop it by the browser's button instead of the conference button. If you use the conference button to stop it the video comes up.
So, I'd say that this issue is because a bad handling of "sharing" status
