### ISSUE TITLE
Building the app as external user, MVN artifact not found.

### ISSUE THREAD

**Issue by Jhoubert** [ant-media/conference-call-application#93]
Since `AMS 2.6.0` has not been officially released yet, mvn files should not [point to 2.6.0,](https://github.com/ant-media/conference-call-application/blob/fe28468d3f88fe8388fc3b03011a88a219cb252c/webapp/pom.xml#L4-L6)

In order to make it build successfully I'm using 2.5.2 which is the latest that I've found in nexus repo:
 
```	
		<groupId>io.antmedia</groupId>
		<artifactId>parent</artifactId>
		<version>2.5.2</version>
```

_BTW: As far I remember 2.5.3 also wont work since antmedia-server is not released, or could be any other reason, just can't remember rn._

@mekya @mustafaboleken Do you think that I should raise a PR for this.?, or the right question is, how long would take releasing 2.6.0.? if it's couple days or so, would be worthless.

Cheers!

**Comment by Jhoubert** [comment]
Since I've started digging into [ant-media-server's](https://github.com/ant-media/Ant-Media-Server) code I've found  that this is also happening in [Ant-Media-Server](https://github.com/ant-media/Ant-Media-Server/blob/b9277086fc461175891422e36781c7c71e3a6019/pom.xml#L3-L5C5). I can completely understand that you're working over it. but as non-org part it's being a little struggling.

**Comment by mustafaboleken** [comment]
Hi @Jhoubert,
As soon as we release a new version, we change the artifact version to the next beta version. To be able to build the conference call application or Ant Media Server project, you can use [parent project](https://github.com/ant-media/ant-media-server-parent) to get the latest artifact.(For today, it's 2.6.0) So, you don't need to wait for next release. For more information, you can check [this documentation](https://antmedia.io/docs/guides/advanced-usage/building-ams-from-source-code/).

**Comment by Jhoubert** [comment]
Oh, cool, didn't know there were another project for building it!
Thanks for pointing it out!

**Comment by mekya** [comment]
Hi @Jhoubert,

2.6.0 is released.
It's available in Maven repo. 
https://mvnrepository.com/artifact/io.antmedia/parent

SNAPSHOT s are also available in sonatype
https://oss.sonatype.org/#nexus-search;gav~io.antmedia~parent~~~~kw,versionexpand

Take care
Oguz

**Comment by mekya** [comment]
Hi @Jhoubert,
I've just sent a connection request on LinkedIn to you. I think we can do something more together :)

**Comment by Jhoubert** [comment]
> Hi @Jhoubert,
> 
> 2.6.0 is released.
> It's available in Maven repo. 
> https://mvnrepository.com/artifact/io.antmedia/parent
> 
> SNAPSHOT s are also available in sonatype
> https://oss.sonatype.org/#nexus-search;gav~io.antmedia~parent~~~~kw,versionexpand
> 
> Take care
> Oguz

Hi @mekya Thanks for the update, I'll build the new version!
